http:
  routers:
    bot-router:
      rule: Host(`${DOMAIN}`)
      service: bot-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    bot-service:
      loadBalancer:
        servers:
          - url: http://bot:80